version: '3'
services:

  spring-app:
    container_name: spring-app
    image: spring-app
    restart: always
    ports:
      - "8080:8080"

  redis1:
    container_name: redis_1
    image: redis:7.0.5
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis2:
    container_name: redis_2
    image: redis:7.0.5
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis3:
    container_name: redis_3
    image: redis:7.0.5
    ports:
      - "6381:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]